[project]
name = "antifraud-api"
version = "0.1.0"
description = "Antifraud Service API"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.109.2",
    "pydantic==2.6.0",
    "python-dateutil==2.8.2",
    "uvicorn[standard]==0.27.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"